### PR TITLE
extension-development folder

### PR DESCRIPTION
**Pull request by Hyper-Node**
# MaRDI Pull Request

**Changes**:
- Adding a folder for storing extensions in development
- Same ide view can be used for files and extensions

**Instructions for PR review**:
- [ ] Conceptual Review (Logic etc...) 
- [x] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [x] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [x] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Comment by physikerwelt** [comment]
can we call the folder just dev?

**Comment by physikerwelt** [comment]
@Hyper-Node what do you think?

**Comment by Hyper-Node** [comment]
> @Hyper-Node what do you think?

I think when naming it extesions-dev it is more obvious what is stored in the folder.

**Comment by physikerwelt** [comment]
Maybe it would be better to link to https://stackoverflow.com/a/1753078 in the main git configuration and give everyone the chance to name her folders as wanted.

**Comment by Hyper-Node** [comment]
If its constant then readme.md can be adapted to mount this specific folder.

**Review by physikerwelt — APPROVED** [review]
While I personally do not find this very useful, I don't want to hold this effort back.

**Pull request merged**
