### PR TITLE
Fix GUI statement links

### PR DESCRIPTION
**Pull request by eloiferrer**
# MaRDI Pull Request

**Changes**:
- This is an attempt to fix https://github.com/MaRDI4NFDI/portal-compose/issues/386 by changing the paths.
- This also fixes a couple of mistakes regarding the env variables in docker-compose.yml

**Instructions for PR review**:
- [ ] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Review by physikerwelt — CHANGES_REQUESTED** [review]
I think it would be better to overwrite the values for local development. If we merged this as it is it would break the staging software links.

**Comment by eloiferrer** [comment]
Isn't here some variable that saves the portal.mardi4nfdi.de url and that can be accessed from Wikibase.php? It somehow doesn't look right to have this hard-coded urls in there.

**Comment by physikerwelt** [comment]
I think this is the variable to be set. Maybe there is something like concept URI from the  linkedwiki extension, but I don't know.

**Review by physikerwelt — APPROVED** [review]
I would have used getenv instead of _ENV but it does not really matter. Decide on your own feelings https://stackoverflow.com/a/8798318

**Comment by eloiferrer** [comment]
Ok. Since we will have now a PORTAL_HOST variable with portal.mardi4nfdi.de as value, would it be ok if I change all the instances of portal.mardi4nfdi.${TLD} in docker-compose.yml to just ${PORTAL_HOST}? e.g. quickstatements.portal.mardi4nfdi.${TLD} to quickstatements.${PORTAL_HOST} and so on.

**Review by physikerwelt — COMMENTED** [review]
I think so.

**Comment by eloiferrer** [comment]
@physikerwelt I changed the logic again, so maybe just take a final look, before I merge it.

**Review by physikerwelt — APPROVED** [review]
I think it is ok, however, I find maintaining the localhost:port alternative creates a huge overhead and makes the dev environment different from production so that some parts need to developed twice. I would thus recommend to remove the localhost:port alternative and use a pseudo domain that points to localhost instead.

**Comment by eloiferrer** [comment]
I don't see if that is really the case here. This implementation does not change the current workflow we have. We are already changing the WIKIBASE_HOST and PORT for development (https://github.com/MaRDI4NFDI/portal-compose/blob/f5ef817eaebb8aeda59447c23f8051ee77608a8c/README.md?plain=1#L21). So no changes in the current dev environment are needed.

**Comment by physikerwelt** [comment]
> I don't see if that is really the case here. This implementation does not change the current workflow we have. 

Yes, I fully agree. So it is as bad as it was before:-)

> We are already changing the WIKIBASE_HOST and PORT for development

At least when trying to get quick statements to run, I found the combination of hosts and ports quite confusing.

https://github.com/MaRDI4NFDI/portal-compose/blob/f5ef817eaebb8aeda59447c23f8051ee77608a8c/docker-compose.yml#L321-L328

For example, `https://quickstatements.portal.mardi4nfdi.${TLD}` points to nowhere in local dev.

This PR, in particular,

https://github.com/MaRDI4NFDI/portal-compose/pull/387/files#diff-1593a24ff7c433502c819e45226b229d3c70082067e354b7208944164926a3f0R9-R13

adds further technical debts to handle both cases, dev, and prod. Instead, I suggest it would be easier to guide developers to install a custom DNS like described here https://github.com/bnfinet/docker-dns

**Comment by physikerwelt** [comment]
@eloiferrer what do you think?

I checked https://staging.swmath.org/wiki/Mathoid and saw that the link to the MaRDI portal item is currently missing, but the other direction from https://portal.mardi4nfdi.de/wiki/Item:Q38023 works. So that needs to be fixed anyhow. So I think it would be a good time to merge this now.

**Pull request merged**
