### PR TITLE
Fix failing tests 

### PR DESCRIPTION
**Pull request by eloiferrer**
# MaRDI Pull Request

**Changes**:
- Update ElasticSearch version in template.env (otherwise local development fails)
- Add variables to template.env to reestablish consistency with the production .env file and avoid warnings in local development.
- Fix typos regarding Matomo analytics
- This is expected to fix the GUI tests

**Instructions for PR review**:
- [X] Conceptual Review (Logic etc...) 
- [X] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Comment by eloiferrer** [comment]
This fixes the selenium tests for portal-compose (https://github.com/MaRDI4NFDI/portal-compose/issues/352), but backup tests fail now due to the newly installed WikibaseExport extension (backup tests pass when deactivating the extension).

@physikerwelt, from the error message, maybe you have a clue what might be going wrong? I've tried a couple of things, with no success so far.

**Comment by physikerwelt** [comment]
Lets's merge this for now and fix the backup image

https://github.com/MaRDI4NFDI/docker-backup/blob/28d7891e7b2de8f32038fead0410120535d991dc/Dockerfile#LL1C11-L1C12

later

**Comment by eloiferrer** [comment]
Ok great, yes, I'll do that.

**Comment by eloiferrer** [comment]
This is now done, see https://github.com/MaRDI4NFDI/docker-backup/pull/38.

**Pull request merged**
