### PR TITLE
New volume

### PR DESCRIPTION
**Pull request by aot29**
# MaRDI Pull Request
We have a shared volume: /var/www/html from mardi-wikibase is shared with wikibase_jobrunner and backup services. As the volume is mounted on mardi-wikibase, it masks any changes to the /var/www/html folder. So every time something new is added in this folder, we have to create a new volume. This problem affects the new Layout, as the /var/www/html /skins folder is in the image, however it does not show up.

We don't want to erase the old volume just in case. Renaming volumes (e.g. shared_mardi_wikibase_OLD) is apparently not possible in Docker.

Anybody got a better idea?

**Changes**:
- portal-compose shared volume is now named "shared_mardi_wikibase_02"

**Instructions for PR review**:
- [x] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [x] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [x] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Review by physikerwelt — CHANGES_REQUESTED** [review]
I don't understand the concept of sharing everything under /var/www/html/ I would rather recommend to replicate the mounts from the mardi wikibase instance and possible additional very specific mounts we need to share config.

Maybe this configuration is an artifact that was copied from here

https://github.com/wmde/wikibase-release-pipeline/blob/73f9942ebd92ded5f17fbb7f8537e9f2268e2bc4/example/docker-compose.yml#L29

While this example helps for an initial fast config, I think it is not suitable for our usecase.

**Comment by aot29** [comment]
Could you be more specific, what do you mean by "replicate the mounts"?

**Comment by physikerwelt** [comment]
the mounts are

https://github.com/MaRDI4NFDI/portal-compose/pull/120/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R34-R36

with replicate I mean to also put these definitions to the jobrunner and ? container

**Comment by physikerwelt** [comment]
to test this you can simply delete the current volume, the effect is the same modulo renaming;-)

**Comment by physikerwelt** [comment]
You can create a backup of the current disk if you like using the method described here https://mardi.formulasearchengine.com/wiki/Project:Backups

**Comment by aot29** [comment]
There's a more elegant solution here: https://github.com/MaRDI4NFDI/portal-compose/pull/124 however, I can't get that solution to work. 

This solution here does work, it will re-run the maintenance scripts so it takes a few minutes to start and leaves an unused volume behind.

**Comment by physikerwelt** [comment]
Please go ahead and try this approach. However, I would just delete the volume and not rename it. So you don't need to change the code at all.

**Comment by aot29** [comment]
Reading the docker-compose settings again requires docker-compose down/up. It's not enough to restart a container. 
I would have of course, but as discussed before in the chat, I can't because I don't have the necessary permissions. If I understand correctly, I would need to run docker as the corresponding user, which I'm not allowed to.

**Comment by physikerwelt** [comment]
> Reading the docker-compose settings again requires docker-compose down/up. It's not enough to restart a container (using Portainer). I would have of course, but as discussed before in the chat, I can't because I don't have the necessary permissions. If I understand correctly, I would need to run docker as the corresponding user, which I'm not allowed to.

I think it is good enough to recreate the container. This is possible from the UI. I can just do it myself. I'll do it right now.

**Comment by physikerwelt** [comment]
Backup is done according to https://portal.mardi4nfdi.de/wiki/Project:Backups. See logs attached
[_backup-creator_logs.txt](https://github.com/MaRDI4NFDI/portal-compose/files/8214123/_backup-creator_logs.txt)

**Comment by physikerwelt** [comment]
The new container has been deployed.

**Comment by aot29** [comment]
Thanks a lot! The status now is: The new layout is online, and the extensions added up to 8 days ago are online. That's a progress compared with the previous situation.

After examining the problem with @LizzAlice, the problem can be seen best in the jobrunner container: 
* Jobrunner uses the same image than wikibase. In the jobrunner container, the EmbedVideo extension is present in /var/www/html/extensions.
* In the jobrunner container, the shared volume is mounted in /shared. In /shared, the EmbedVideo is not present, so in my view this confirms that the volume is masking the extensions in the wikibase container.

**Comment by physikerwelt** [comment]
Thank you for looking into this. My theory is that this is related to https://github.com/MaRDI4NFDI/docker-wikibase/issues/12

**Pull request closed without merging**
