### PR TITLE
Update template.env

### PR DESCRIPTION
**Pull request by Hyper-Node**
# MaRDI Pull Request

**Changes**:
- remove single quotes from env file 
- 
-  

**Instructions for PR review**:
- [x] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Review by dajuno — APPROVED** [review]

**Comment by physikerwelt** [comment]
@dajuno @Hyper-Node can you rebase and merge.

**Comment by physikerwelt** [comment]
@dajuno @Hyper-Node can you rebase and merge.

**Comment by dajuno** [comment]
looks like we're on it simultaneously... I leave this to you @Hyper-Node

**Comment by Hyper-Node** [comment]
ok, see https://github.com/MaRDI4NFDI/portal-compose/pull/254

**Pull request closed without merging**
