### PR TITLE
Use shared configuration

### PR DESCRIPTION
**Pull request by physikerwelt**
This avoids that a new volume has to be created for each commit.

Alternative to https://github.com/MaRDI4NFDI/portal-compose/pull/120

Depends on https://github.com/MaRDI4NFDI/docker-wikibase/pull/9 and https://github.com/MaRDI4NFDI/docker-backup/pull/9

# MaRDI Pull Request

**Changes**:
- 
- 
-  

**Instructions for PR review**:
- [ ] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Review by aot29 — COMMENTED** [review]
This is an excellent solution. However, when I rebuild docker-wikibase, docker-backup and start the services using the new docker-compose, the wikibase fails to start. I'm still trying to find out why.

**Comment by aot29** [comment]
I can't get it to work. See also https://github.com/MaRDI4NFDI/portal-compose/pull/125.
I think we need a staging instance on the server to try it out and the necessary permissions to do docker using ssh, not through Portainer.

**Comment by physikerwelt** [comment]
> I can't get it to work. See also #125. I think we need a staging instance on the server to try it out and the necessary permissions to do docker using ssh, not through Portainer. Something like this does it: stop the containers, erase the volumes, start the containers, restore from backup.

I think this is what the CI should do? Or do you mean some beta like mardi.beta.wmflabs.org? In the next iterations, we will have two instances running at zib. One can run from master and the other one from a release tag.

**Comment by aot29** [comment]
Ideally yes, but I find the CI difficult to debug and as long as new features are added with no tests, it's not getting any easier. Having a beta would perhaps be a viable alternative.

**Comment by dajuno** [comment]
at least locally this causes ever repeating log messages `portal-compose-wikibase_jobrunner-1  | LocalSettings.php not shared yet - waiting for 10 seconds.`

this did not happen with 72ccbb2 (and earlier, probably). is this theorrect behavior?

(ps: I had commented this on the [commit](https://github.com/MaRDI4NFDI/portal-compose/commit/a7117b6c99f72f5e9a1ce41d3895f37d2955a38f#commitcomment-68407345) directly, copied here, too)

**Comment by physikerwelt** [comment]
> Depends on [MaRDI4NFDI/docker-wikibase#9](https://github.com/MaRDI4NFDI/docker-wikibase/pull/9) and [MaRDI4NFDI/docker-backup#9](https://github.com/MaRDI4NFDI/docker-backup/pull/9)

Do you have the latest versions of the containers? Maybe also run docker-compose down and up.

**Comment by dajuno** [comment]
indeed, I had overlooked that. It runs fine with updated images. thanks

**Pull request merged**
