### PR TITLE
assign container_name mardi-backup to backup container (fixes #117)

### LINKED ISSUE #117: backup test failure due to inconsistent automatic container names
**Bug description**
`bash run_tests.sh` fails for the backup test, on archlinux (linux 5.16) using docker-compose 2.2.3:

```
Test the backup functions                                                                                                                                                 
----------------------------------------                                                                                                                                  
Error: No such container: portal-compose_backup_1
```

The container is named `portal-compose-backup-1` on my machine.

**Expected behavior**

all tests should pass.

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

### PR DESCRIPTION
**Pull request by dajuno**
# MaRDI Pull Request

**Changes**:
- backup gets `container_name: mardi-backup`
- container name is modified accordingly in `run_tests.sh`

**Instructions for PR review**:
- [ ] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [x] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Comment by dajuno** [comment]
commit c8601e3 proposes a fix of the CI backup test, accordingly. not quite sure if this is the correct workflow, please comment

**Comment by Hyper-Node** [comment]
Workflow tbd: Assign technically related person for review. If PR is approved in Review, merge the branch to main. Delete the branch then.

**Comment by dajuno** [comment]
> Workflow tbd: Assign technically related person for review.

i.e., request you or alvaro?

**Review by aot29 — APPROVED** [review]
Tried it out locally, looking good. Thanks for spotting this.

**Comment by aot29** [comment]
The current settings require you to sign the commits. https://docs.github.com/articles/about-gpg/

**Pull request merged**
